# Generated by Django 4.2 on 2023-04-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ingredient_name_scientific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food_subgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='wikipedia_id',
            field=models.URLField(null=True),
        ),
    ]
